[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2021"

[lib]
path ="src/lib.rs"

[dependencies]
bincode = "1.3.3"
num-bigint = "0.4.6"
serde = { version = "1.0", features = ["derive"] }
sled = "0.34.7"

